### ISSUE TITLE
Cannot pull or download any civitai's lora!

### ISSUE THREAD

**Issue by bachdyon** [replicate/flux-fine-tuner#41]
I tried many times but it did not work.
![CleanShot 2024-10-01 at 22 17 47](https://github.com/user-attachments/assets/0e6eff18-061d-45fe-8c6f-1568217eed56)

https://civitai.com/models/726732/realistic-people-photograph-flux

Using seed: 1666
Prompt: A photo of XXXX, A high-quality photo of a young woman with a graceful and confident presence, standing on a white sandy beach. She is wearing a vibrant orange bodycon and long bikini that accentuates her elegant figure. Coconut trees sway gently in the background, and the ocean's calm waves reflect the soft sunlight. Her expression is poised and serene, with a warm breeze adding movement to the scene, creating a peaceful and refreshing beach atmosphere.

[!] txt2img mode
Using dev model
Loading extra LoRA weights from: https://civitai.com/models/458635/goth-emo-girl-lora-flux-sdxl
free=2915395551232
Downloading weights
2024-10-01T14:47:58Z | INFO  | [ Initiating ] chunk_size=150M dest=/src/weights-cache/d31491da43869694 url=https://civitai.com/api/download/models/458635?type=Model&format=SafeTensor
Error: unexpected http status https://civitai.com/api/download/models/458635?type=Model&format=SafeTensor: 404 Not Found
Traceback (most recent call last):
File "/src/weights.py", line 148, in download_safetensors
subprocess.run(["pget", url, str(path)], check=True)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pget', 'https://civitai.com/api/download/models/458635?type=Model&format=SafeTensor', '/src/weights-cache/d31491da43869694']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 352, in _predict
result = predict(**payload)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 377, in predict
self.load_multiple_loras(replicate_weights, extra_lora, model)
File "/src/predict.py", line 463, in load_multiple_loras
extra_lora_path = self.weights_cache.ensure(extra_lora_url)
File "/src/weights.py", line 45, in ensure
download_weights(url, path)
File "/src/weights.py", line 74, in download_weights
download_weights_url(download_url, path)
File "/src/weights.py", line 88, in download_weights_url
download_safetensors(url, path)
File "/src/weights.py", line 150, in download_safetensors
raise RuntimeError(f"Failed to download safetensors file: {e}")
RuntimeError: Failed to download safetensors file: Command '['pget', 'https://civitai.com/api/download/models/458635?type=Model&format=SafeTensor', '/src/weights-cache/d31491da43869694']' returned non-zero exit status 1.

**Comment by CristianFigueredo** [comment]
I cannot use any extra lora, @bachdyon hf or replicate loras work for you?

**Comment by lucataco** [comment]
When attempting to go to the link: [https://civitai.com/models/726732/realistic-people-photograph-flux](https://civitai.com/models/726732/realistic-people-photograph-flux)

I see the message: 
> The creator of this LoRA has set this version to Early Access and as such it is only available for people who purchase it. This LoRA will be available for free in 8 days, 15 hours, and 48 minutes

**Comment by bossjones** [comment]
Hi all, thanks for all the hard work.

I came across another issue like this where the user requires someone to be logged in to download the safetensor file. Looks like there's a workaround if you generate an api key. https://education.civitai.com/civitais-guide-to-downloading-via-api/

example repo: https://civitai.com/models/387270/starship-troopers-sdxl
