### ISSUE TITLE
Extra LoRa is not working anymore 

### ISSUE THREAD

**Issue by CristianFigueredo** [replicate/flux-fine-tuner#44]
<img width="1512" alt="Screenshot 2024-10-08 at 6 14 47 PM" src="https://github.com/user-attachments/assets/0701c436-b649-4dc4-aafa-c7407e908cec">
<img width="1512" alt="Screenshot 2024-10-08 at 6 15 34 PM" src="https://github.com/user-attachments/assets/39e52b5b-e246-4cc0-931c-46c457fdb531">

Full log
`Using seed: 1655
Prompt: a woman
[!] txt2img mode
Using dev model
Loading extra LoRA weights from: https://huggingface.co/XLabs-AI/flux-RealismLora
free=7358052478976
Downloading weights
2024-10-08T21:12:59Z | INFO  | [ Initiating ] chunk_size=150M dest=/tmp/tmpmwmwg850/weights url=https://replicate.delivery/yhqm/3JgwN0M49PIOM1z8l2hdhXnZg784eZilm9oGsqeDuVHC8AdTA/trained_model.tar
2024-10-08T21:13:01Z | INFO  | [ Complete ] dest=/tmp/tmpmwmwg850/weights size="172 MB" total_elapsed=2.689s url=https://replicate.delivery/yhqm/3JgwN0M49PIOM1z8l2hdhXnZg784eZilm9oGsqeDuVHC8AdTA/trained_model.tar
Downloaded weights in 2.72s
free=7357880475648
Downloading weights
2024-10-08T21:13:02Z | INFO  | [ Initiating ] chunk_size=150M dest=/src/weights-cache/20d9eb963e82841f url=https://huggingface.co/XLabs-AI/flux-RealismLora/resolve/main/lora.safetensors
2024-10-08T21:13:03Z | INFO  | [ Redirect ] redirect_url=https://cdn-lfs-us-1.hf.co/repos/b2/dc/b2dc0cd6006db80c21ccfb2904f6eab00b2dc3eb587a0a438271b81d8b432c69/0a83a924b822b70b5e458d27935ebfa7713edaee04ff9f194209525354031eca?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27lora.safetensors%3B+filename%3D%22lora.safetensors%22%3B&Expires=1728681182&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyODY4MTE4Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2IyL2RjL2IyZGMwY2Q2MDA2ZGI4MGMyMWNjZmIyOTA0ZjZlYWIwMGIyZGMzZWI1ODdhMGE0MzgyNzFiODFkOGI0MzJjNjkvMGE4M2E5MjRiODIyYjcwYjVlNDU4ZDI3OTM1ZWJmYTc3MTNlZGFlZTA0ZmY5ZjE5NDIwOTUyNTM1NDAzMWVjYT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=jRxW0KKA2OBeIiK%7EjB1vnpHcln%7ETmGFxZ3VP808y%7E4rLxfhmhffwoLZxSVYWdQxyTVZtimNqtTqIzDSLzSaMQ649crr5P5ncAcCmpDt%7EBYRmISD%7E-CbQpCn3TRUcKr0UlzD4L2fu25zXQDKOKytSfE3ojhprxBIoEl9tsutZzBba7T7y37nFiOvYs9y7nJvRyObKkQi%7EJz8XG-bkto2nNuqRm3mHkoW%7Etsk6VaB1XEgtmqPKh0ST0qbnba%7E2UNsG3b-gYKQo-V9fMtRrRLVmcdgtWNoy8q82p9G771asrfL0REnVWsg08qoe%7EPV3fKnNYbVggsKAzITQ4U6zJgODqw__&Key-Pair-Id=K24J24Z295AEI9 url=https://huggingface.co/XLabs-AI/flux-RealismLora/resolve/main/lora.safetensors
2024-10-08T21:13:03Z | INFO  | [ Complete ] dest=/src/weights-cache/20d9eb963e82841f size="22 MB" total_elapsed=0.954s url=https://huggingface.co/XLabs-AI/flux-RealismLora/resolve/main/lora.safetensors
Downloaded weights in 0.98s
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 377, in predict
self.load_multiple_loras(replicate_weights, extra_lora, model)
File "/src/predict.py", line 469, in load_multiple_loras
pipe = pipe.to("cuda")
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 435, in to
module.to(device, dtype)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
return self._apply(convert)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
[Previous line repeated 3 more times]
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
param_applied = fn(param)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1167, in convert
raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.`

**Comment by lucataco** [comment]
For Xlabs-AI LoRAs, please use the Comfy converted ones here:
[https://huggingface.co/XLabs-AI/flux-lora-collection](https://huggingface.co/XLabs-AI/flux-lora-collection/tree/main)

**Comment by CristianFigueredo** [comment]
<img width="1512" alt="Screenshot 2024-10-09 at 1 09 34 PM" src="https://github.com/user-attachments/assets/bca8290f-b756-4de0-8eff-c8d65b7d7739">
I'm doing something wrong @lucataco?

**Comment by lucataco** [comment]
That is the wrong URL, you should see the word "resolve" in the URL (not "tree")
Be sure to click the "Copy download link" button
