### ISSUE TITLE
Training failed - FLUX.1-dev/transformer is not a local folder

### ISSUE THREAD

**Issue by replicategithubwc** [replicate/flux-fine-tuner#53]
I am encountering a training failed error upon creating a training in Replicate both via Web and API using this model https://replicate.com/ostris/flux-dev-lora-trainer/train. I am inputting 1000 steps, zip file for the images, and a trigger word and keeping every input as default.

This is a screenshot of the error messsage:
<img width="661" alt="Screen Shot 2024-10-16 at 2 02 26 PM" src="https://github.com/user-attachments/assets/787e05af-7f0b-4373-ba9a-e752391e61aa">

```
Running  1 process
Loading Flux model
Loading transformer
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
response.raise_for_status()
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/FLUX.1-dev/transformer/resolve/main/config.json
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 379, in load_config
config_file = hf_hub_download(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
return f(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
return _hf_hub_download_to_cache_dir(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1347, in _hf_hub_download_to_cache_dir
_raise_on_head_call_error(head_call_error, force_download, local_files_only)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1854, in _raise_on_head_call_error
raise head_call_error
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1751, in _get_metadata_or_catch_error
metadata = get_hf_file_metadata(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1673, in get_hf_file_metadata
r = _request_wrapper(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 376, in _request_wrapper
response = _request_wrapper(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 400, in _request_wrapper
hf_raise_for_status(response)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-670f54c7-2bdd4f1f05165d5004effc01;3c542653-ff73-4c8f-9f90-cbf38f0fb5cc)
Repository Not Found for url: https://huggingface.co/FLUX.1-dev/transformer/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
File "/src/train.py", line 355, in train
job.run()
File "/src/train.py", line 97, in run
process.run()
File "/src/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1241, in run
self.sd.load_model()
File "/src/ai-toolkit/toolkit/stable_diffusion_model.py", line 488, in load_model
transformer = FluxTransformer2DModel.from_pretrained(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 612, in from_pretrained
config, unused_kwargs, commit_hash = cls.load_config(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 394, in load_config
raise EnvironmentError(
OSError: FLUX.1-dev/transformer is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
```

**Comment by Saquib764** [comment]
I am also facing the same issue. The exact same call works sometimes, and sometimes it don't.

**Comment by lucataco** [comment]
This should be fixed for both web and API now. If you are trying to use Flux locally you will have to download from huggingface since it is a gated model per the license agreement
