### ISSUE TITLE
config.json missing

### ISSUE THREAD

**Issue by TheStu** [replicate/flux-fine-tuner#54]
I get this error when attempting to use the web form for training:
```
Training failed.
Error no file named config.json found in directory FLUX.1-dev/transformer.
```

form inputs:
```
{
  "steps": 1000,
  "lora_rank": 16,
  "optimizer": "adamw8bit",
  "batch_size": 1,
  "resolution": "512,768,1024",
  "autocaption": true,
  "input_images": "https://replicate.delivery/pbxt/Lo2g1RgMZIrlGveIVGRcmwP4sL5UFP3PaYARmh6CclftYuaq/flux.zip",
  "trigger_word": "TOK",
  "learning_rate": 0.0004,
  "wandb_project": "flux_train_replicate",
  "wandb_save_interval": 100,
  "caption_dropout_rate": 0.05,
  "cache_latents_to_disk": false,
  "wandb_sample_interval": 100
}
```

full log:
```
Starting train job
{
"type": "custom_sd_trainer",
"training_folder": "output",
"device": "cuda:0",
"trigger_word": "TOK",
"network": {
"type": "lora",
"linear": 16,
"linear_alpha": 16
},
"save": {
"dtype": "float16",
"save_every": 1001,
"max_step_saves_to_keep": 1
},
"datasets": [
{
"folder_path": "input_images",
"caption_ext": "txt",
"caption_dropout_rate": 0.05,
"shuffle_tokens": false,
"cache_latents_to_disk": false,
"cache_latents": true,
"resolution": [
512,
768,
1024
]
}
],
"train": {
"batch_size": 1,
"steps": 1000,
"gradient_accumulation_steps": 1,
"train_unet": true,
"train_text_encoder": false,
"content_or_style": "balanced",
"gradient_checkpointing": true,
"noise_scheduler": "flowmatch",
"optimizer": "adamw8bit",
"lr": 0.0004,
"ema_config": {
"use_ema": true,
"ema_decay": 0.99
},
"dtype": "bf16"
},
"model": {
"name_or_path": "FLUX.1-dev",
"is_flux": true,
"quantize": true
},
"sample": {
"sampler": "flowmatch",
"sample_every": 1001,
"width": 1024,
"height": 1024,
"prompts": [],
"neg": "",
"seed": 42,
"walk_seed": true,
"guidance_scale": 3.5,
"sample_steps": 28
}
}
Using EMA
#############################################
# Running job: flux_train_replicate
#############################################
Running  1 process
Loading Flux model
Loading transformer
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 352, in _predict
result = predict(**payload)
File "/src/train.py", line 355, in train
job.run()
File "/src/train.py", line 97, in run
process.run()
File "/src/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1241, in run
self.sd.load_model()
File "/src/ai-toolkit/toolkit/stable_diffusion_model.py", line 488, in load_model
transformer = FluxTransformer2DModel.from_pretrained(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 612, in from_pretrained
config, unused_kwargs, commit_hash = cls.load_config(
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 373, in load_config
raise EnvironmentError(
OSError: Error no file named config.json found in directory FLUX.1-dev/transformer.
```

**Comment by billnye2** [comment]
Also getting this issue

**Comment by billnye2** [comment]
Looks like it's working now

**Comment by DomEscobar** [comment]
Still this issue

**Comment by liebisca** [comment]
I got this error sometime. It is covered by my retry logic, but sometimes it still appears in the error logs.

**Comment by ParvinEyvazov** [comment]
Same error :(

**Comment by ParvinEyvazov** [comment]
It seems that some of my training sessions are failing due to version changes. 
Would it be possible to have a more stable version system @lucataco? It looks like new versions are automatically overriding older ones used in the code, which leads to unexpected errors. We often need to check the platform to see what’s happening.

For example, in one case, my initial training failed, but when I reran the exact same code (which used version "29337367d801d93e9193dafd8fcfb5653eeacd841fe85db9118023fbb" and was automatically updated to "e440909d3512c31646ee2e0c7d6f6f4923224863a6a10c494606e79fb5844497" by the platform in both runs), it worked the second time without any changes.

Both are exact same inputs.

![Screenshot 2024-10-21 at 19 59 15](https://github.com/user-attachments/assets/c9027792-6937-4234-a4ce-768a6f17449c)

**Comment by simonpicard** [comment]
same error today

**Comment by 921kiyo** [comment]
Facing the same error today

**Comment by hardikdava** [comment]
+1

**Comment by simonpicard** [comment]
Hey @lucataco would you have any insights into this issue? Many thanks for the help.

**Comment by lucataco** [comment]
This should be fixed now
